# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

first_names = %w[Avery Jordan Taylor Morgan Riley Casey Jamie Cameron Quinn Parker]
last_names = %w[Anderson Bennett Chen Diaz Evans Foster Gupta Hughes]
companies = [
  "Acme Labs", "Brightside Studio", "Cedar & Co.", "Evergreen Systems",
  "Harbor Consulting", "Northstar Media", "Summit Works", "Willow Partners"
]
job_titles = [
  "Account Manager", "Business Analyst", "Creative Director", "Engineer",
  "Marketing Manager", "Operations Lead", "Product Designer", "Sales Director"
]
locations = [
  { city: "Austin", state: "TX", postal_code: "78701", country: "United States" },
  { city: "Chicago", state: "IL", postal_code: "60601", country: "United States" },
  { city: "London", state: "England", postal_code: "EC1A 1BB", country: "United Kingdom" },
  { city: "Toronto", state: "ON", postal_code: "M5H 2N2", country: "Canada" },
  { city: "Sydney", state: "NSW", postal_code: "2000", country: "Australia" }
]

40.times do |index|
  first_name = first_names[index % first_names.length]
  last_name = last_names[index % last_names.length]
  location = locations[index % locations.length]
  email = "contact#{index + 1}@example.com"

  Contact.find_or_create_by!(email:) do |contact|
    contact.assign_attributes(
      first_name:,
      last_name:,
      phone: "+1 555 #{format("%03d", 100 + index)} #{format("%04d", 1000 + index)}",
      company: companies[index % companies.length],
      job_title: job_titles[index % job_titles.length],
      address: "#{100 + index} Example Street",
      notes: "Demo contact generated by db:seed.",
      **location
    )
  end
end
